### ISSUE TITLE
Fix horizontal scroll bar

### ISSUE THREAD

**Issue by ce-yasser** [imranbaig123/angular-freelance-project#12]
Some element is creating a horizontal scroll bar, please identify it and fix it
![image](https://github.com/imranbaig123/angular-freelance-project/assets/84215288/bb1d5405-0a90-4166-8393-674b9646b437)

**Comment by ce-yasser** [comment]
payment-box, remove the 11% margin and use flex box to center the content
![image](https://github.com/imranbaig123/angular-freelance-project/assets/84215288/23eb7298-5c9b-4ed0-a63c-42f040a805b1)

**Comment by imranbaig123** [comment]
closed #12
