### ISSUE TITLE
Remove the extra <head> in the body 

### ISSUE THREAD

**Issue by ce-yasser** [imranbaig123/angular-freelance-project#5]
the page can't have multiple <head> tag and the <head> can't be inside the body
Remove the extra head in the body and use the recommended methods to call css file 
[https://ej2.syncfusion.com/angular/documentation/common/how-to/custom-css](https://ej2.syncfusion.com/angular/documentation/common/how-to/custom-css)

![image](https://github.com/imranbaig123/angular-freelance-project/assets/84215288/f4a01fda-c1f6-4b33-8239-758bb3c1c166)

CDN is not working in egypt  ¯_(ツ)_/¯, I would appreciate it if you can use a local version of bootstrap

**Comment by imranbaig123** [comment]
close #5
