### ISSUE TITLE
Buttons horizontal alignment

### ISSUE THREAD

**Issue by ce-yasser** [imranbaig123/angular-freelance-project#7]
The center alignment of the buttons are not correct, using margin-left 30% is not right here.
Please use flexbox to center the buttons.

Wrap the buttons in a single div and use display flex on the parent div to center the buttons, also utilize column gap to add the space between the buttons. No need to use any margins here unless it's for vertical alignment only. 

https://www.flexbox.fun/

![image](https://github.com/imranbaig123/angular-freelance-project/assets/84215288/3d6fd37a-c2b8-4265-80fb-865fbc34635e)

**Comment by imranbaig123** [comment]
closed #7
