### ISSUE TITLE
Button size is not right

### ISSUE THREAD

**Issue by ce-yasser** [imranbaig123/angular-freelance-project#8]
Please match the button height and width with the design. the button should match the design height and width without breaking if the text changed.

Use vertical padding ( top & bottom ) to match the design height (56px), don't use height property
For the width, use min-width with an appropriate horizontal padding, for example 20px padding left and right and min-width: 171px;

![image](https://github.com/imranbaig123/angular-freelance-project/assets/84215288/342ba5b3-ab5b-49f3-b3ef-aed626d2250c)

**Comment by imranbaig123** [comment]
closed #8
