### ISSUE TITLE
Fix layout for 2nd section

### ISSUE THREAD

**Issue by ce-yasser** [imranbaig123/angular-freelance-project#9]
Replace justify-content space-between, and use center.
Use column-gap to match the design gap. 
Use flex-wrap to fix the layout on small devices. also use row-gap to add space between each row on mobile
![image](https://github.com/imranbaig123/angular-freelance-project/assets/84215288/f73f0def-8592-4913-bcc5-57d5c5a9ae78)

**Comment by imranbaig123** [comment]
closed #9
